/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.hexing.tool.vi;

/**
 *
 * @author Administrator
 */
public class ToolFrame extends javax.swing.JFrame {

    /**
     * Creates new form ToolFrame
     */
    public ToolFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_rawFrame = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_afterProcess = new javax.swing.JTextField();
        b_splitFrame = new javax.swing.JButton();
        b_clear = new javax.swing.JButton();
        b_removeSpace = new javax.swing.JButton();
        b_callExplain = new javax.swing.JButton();
        b_callDecriptor = new javax.swing.JButton();
        b_callSysCalc = new javax.swing.JButton();
        b_ascii2String = new javax.swing.JButton();
        b_string2ascii = new javax.swing.JButton();
        b_hexToOct = new javax.swing.JButton();
        b_octToHex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("原始帧：");

        jLabel2.setText("处理后：");

        b_splitFrame.setText("分割帧");
        b_splitFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_splitFrameActionPerformed(evt);
            }
        });

        b_clear.setText("清空");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });

        b_removeSpace.setText("去掉空格");
        b_removeSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removeSpaceActionPerformed(evt);
            }
        });

        b_callExplain.setText("调用解析程序");
        b_callExplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_callExplainActionPerformed(evt);
            }
        });

        b_callDecriptor.setText("调用解密程序");
        b_callDecriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_callDecriptorActionPerformed(evt);
            }
        });

        b_callSysCalc.setText("调用系统计算器");
        b_callSysCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_callSysCalcActionPerformed(evt);
            }
        });

        b_ascii2String.setText("Ascii2String");
        b_ascii2String.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ascii2StringActionPerformed(evt);
            }
        });

        b_string2ascii.setText("String2Ascii");
        b_string2ascii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_string2asciiActionPerformed(evt);
            }
        });

        b_hexToOct.setText("HexToOct");
        b_hexToOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hexToOctActionPerformed(evt);
            }
        });

        b_octToHex.setText("OctToHex");
        b_octToHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_octToHexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_rawFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_afterProcess))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(b_callExplain)
                        .addGap(34, 34, 34)
                        .addComponent(b_callDecriptor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_callSysCalc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_ascii2String, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_splitFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_hexToOct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_string2ascii, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_removeSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_octToHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_rawFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_splitFrame)
                    .addComponent(b_removeSpace))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_afterProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_callDecriptor)
                            .addComponent(b_callExplain)
                            .addComponent(b_callSysCalc)
                            .addComponent(b_clear)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_ascii2String)
                            .addComponent(b_string2ascii))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_hexToOct)
                            .addComponent(b_octToHex))))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_callExplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_callExplainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_callExplainActionPerformed

    private void b_callDecriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_callDecriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_callDecriptorActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_clearActionPerformed

    private void b_removeSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_removeSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_removeSpaceActionPerformed

    private void b_splitFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_splitFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_splitFrameActionPerformed

    private void b_callSysCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_callSysCalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_callSysCalcActionPerformed

    private void b_ascii2StringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ascii2StringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_ascii2StringActionPerformed

    private void b_string2asciiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_string2asciiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_string2asciiActionPerformed

    private void b_hexToOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hexToOctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_hexToOctActionPerformed

    private void b_octToHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_octToHexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_octToHexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ascii2String;
    private javax.swing.JButton b_callDecriptor;
    private javax.swing.JButton b_callExplain;
    private javax.swing.JButton b_callSysCalc;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_hexToOct;
    private javax.swing.JButton b_octToHex;
    private javax.swing.JButton b_removeSpace;
    private javax.swing.JButton b_splitFrame;
    private javax.swing.JButton b_string2ascii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField t_afterProcess;
    private javax.swing.JTextField t_rawFrame;
    // End of variables declaration//GEN-END:variables
}
